// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQCszMktZeAWHWh17cgMj1zXvpvmApC7U',
    appId: '1:161208626137:android:9755c568a183fc3d9d47c8',
    messagingSenderId: '161208626137',
    projectId: 'appmobie-auth-001',
    storageBucket: 'appmobie-auth-001.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi-WMqe0jQhxNM1U_1kRCjvvNJ6U_yM3E',
    appId: '1:161208626137:web:7cb3cd08120303f09d47c8',
    messagingSenderId: '161208626137',
    projectId: 'appmobie-auth-001',
    authDomain: 'appmobie-auth-001.firebaseapp.com',
    storageBucket: 'appmobie-auth-001.firebasestorage.app',
    measurementId: 'G-JXMY88M0RG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwMzn60vhox3RNbwd0XMGDEPSnuf-aD4Q',
    appId: '1:161208626137:ios:85878d71b985f2339d47c8',
    messagingSenderId: '161208626137',
    projectId: 'appmobie-auth-001',
    storageBucket: 'appmobie-auth-001.firebasestorage.app',
    iosBundleId: 'com.example.appmobie',
  );

}